// lib/programs.js

export const programs = [
  {
    id: 1,
    slug: "fat-burn-4w",
    name: "حرق الدهون السريع",
    title: "حرق الدهون السريع — 4 أسابيع",
    subtitle:
      "برنامج مكثّف لحرق الدهون وتحسين اللياقة باستخدام تمارين HIIT وتغذية ذكية",
    goal: "loss",
    duration: "4 أسابيع",
    durationWeeks: 4,
    level: "مبتدئ",
    difficulty: 3,
    sessionsPerWeek: 5,
    avgSessionMinutes: 30,
    homeFriendly: true,
    equipment: ["حصيرة", "زوج دمبلز (اختياري)"],
    tags: ["حرق دهون", "لياقة", "منزلي"],
    price: { SAR: 199, original: 299, discountPercent: 33 },
    image: "/images/program-fatburn.webp",
    hero: {
      image: "/images/program-fatburn.webp",
      video: null,
    },
    badges: [
      { label: "4 أسابيع", type: "time" },
      { label: "5 جلسات/أسبوع", type: "sessions" },
      { label: "30 دقيقة", type: "time" },
      { label: "مبتدئ", type: "level" },
      { label: "منزلي", type: "home" },
    ],
    features: ["تمارين HIIT", "نظام غذائي", "متابعة أسبوعية"],
    overview: {
      about:
        "برنامج مصمم لحرق الدهون بسرعة مع الحفاظ على الكتلة العضلية. مناسب للمبتدئين ويعمل بدون أجهزة معقدة.",
      benefits: [
        "تحفيز الحرق المستمر للدهون",
        "تحسين اللياقة القلبية",
        "زيادة التحمل والطاقة",
        "مرونة في الجدول الزمني",
      ],
      requirements: [
        "مساحة صغيرة",
        "التزام 5 أيام أسبوعيًا",
        "اتباع الخطة الغذائية",
      ],
    },
    stats: {
      estCaloriesPerWeek: 1800,
      intensity: "متوسط",
    },
    weeks: [
      {
        week: 1,
        focus: "تأسيس التحمل والحركة",
        sessions: [
          {
            id: "w1s1",
            day: "السبت",
            title: "HIIT Intro",
            duration: 25,
            equipment: ["حصيرة"],
            goal: "تنشيط الجسم وحرق الدهون",
            exercises: [
              {
                name: "Burpees",
                sets: 3,
                reps: "10",
                restSec: 60,
                demoUrl: "#",
              },
              {
                name: "Jumping Jacks",
                sets: 3,
                reps: "30s",
                restSec: 30,
                demoUrl: "#",
              },
              {
                name: "Mountain Climbers",
                sets: 3,
                reps: "30s",
                restSec: 30,
                demoUrl: "#",
              },
            ],
          },
          {
            id: "w1s2",
            day: "الأحد",
            title: "Lower Body Burn",
            duration: 30,
            equipment: ["حصيرة"],
            goal: "حرق دهون الساقين",
            exercises: [
              {
                name: "Squats",
                sets: 4,
                reps: "15",
                restSec: 60,
                demoUrl: "#",
              },
              {
                name: "Lunges",
                sets: 3,
                reps: "12/leg",
                restSec: 60,
                demoUrl: "#",
              },
            ],
          },
        ],
      },
      // يمكن إضافة باقي الأسابيع لاحقًا
    ],
    nutrition: {
      macros: { calories: 1800, protein: 120, carbs: 180, fat: 50 },
      sampleMeals: [
        { meal: "فطور", items: ["شوفان", "موز", "بيض مسلوق"] },
        { meal: "غداء", items: ["دجاج مشوي", "أرز بني", "خضار"] },
        { meal: "سناك", items: ["زبادي", "لوز"] },
        { meal: "عشاء", items: ["سلمون", "بطاطا حلوة", "سلطة"] },
      ],
      note: "يمكن تعديل السعرات حسب الوزن والهدف.",
    },
    trainers: [
      {
        id: "t1",
        name: "Coach Ahmed",
        avatar: "/images/CoachAhmed.webp",
        rating: 4.7,
        certs: ["CPT", "Nutrition Coach"],
        bio: "متخصص في تمارين HIIT وبرامج الحرق.",
      },
    ],
    reviews: [
      {
        id: "r1",
        user: "Layla",
        rating: 5,
        text: "فقدت 3 كيلو في أسبوعين!",
        date: "2025-07-15",
      },
      {
        id: "r2",
        user: "Khalid",
        rating: 4,
        text: "جيد جدًا، لكن التمارين متعبة.",
        date: "2025-07-20",
      },
    ],
    faq: [
      { q: "هل يمكنني تعديل الجدول؟", a: "نعم، يمكن تعديل الأيام حسب جدولك." },
      { q: "هل أحتاج معدات؟", a: "لا، يمكن الأداء بدون أوزان." },
    ],
  },
  {
    id: 2,
    slug: "muscle-gain-8w",
    name: "زيادة العضلات",
    title: "زيادة العضلات — 8 أسابيع",
    subtitle: "برنامج تضخيم متكامل مع خطة بروتين وتغذية متخصصة",
    goal: "muscle",
    duration: "8 أسابيع",
    durationWeeks: 8,
    level: "متوسط",
    difficulty: 4,
    sessionsPerWeek: 6,
    avgSessionMinutes: 60,
    homeFriendly: false,
    equipment: ["أوزان حرة", "آلات الجيم"],
    tags: ["تضخيم", "قوة", "جيم"],
    price: { SAR: 399, original: 499, discountPercent: 20 },
    image: "/images/program-muscle.webp",
    hero: {
      image: "/images/program-muscle.webp",
      video: null,
    },
    badges: [
      { label: "8 أسابيع", type: "time" },
      { label: "6 جلسات/أسبوع", type: "sessions" },
      { label: "60 دقيقة", type: "time" },
      { label: "متوسط", type: "level" },
      { label: "جيم", type: "gym" },
    ],
    features: ["تدريبات تضخيم", "بروتين يومي", "استشفاء مثالي"],
    overview: {
      about:
        "برنامج تضخيم مكثّف يركّز على تضخيم العضلات باستخدام تمارين تضخيم موجهة وتغذية غنية بالبروتين.",
      benefits: [
        "زيادة الكتلة العضلية",
        "تحسين القوة والقدرة على التحمل",
        "استشفاء مثالي بين الجلسات",
        "خطة بروتين يومية",
      ],
      requirements: [
        "الوصول إلى جيم",
        "التزام 6 أيام أسبوعيًا",
        "تناول 1.8 جرام بروتين/كجم",
      ],
    },
    stats: {
      estCaloriesPerWeek: 2500,
      intensity: "عالٍ",
    },
    weeks: [],
    nutrition: {
      macros: { calories: 2800, protein: 180, carbs: 300, fat: 80 },
      sampleMeals: [
        { meal: "فطور", items: ["بيض", "شوفان", "موز"] },
        { meal: "غداء", items: ["دجاج", "أرز", "خضار"] },
        { meal: "سناك", items: ["بروتين شيك", "مكسرات"] },
        { meal: "عشاء", items: ["لحم", "بطاطا", "سلطة"] },
      ],
      note: "يُنصح بتناول بروتين بعد كل جلسة.",
    },
    trainers: [
      {
        id: "t2",
        name: "Coach Omar",
        avatar: "/images/CoachOmar.webp",
        rating: 4.9,
        certs: ["CSCS", "Strength Coach"],
        bio: "متخصص في التضخيم والقوة.",
      },
    ],
    reviews: [
      {
        id: "r3",
        user: "Fahad",
        rating: 5,
        text: "نتائج مذهلة، أنصح به لكل من يبحث عن عضلات.",
        date: "2025-07-18",
      },
    ],
    faq: [
      { q: "هل يمكنني البدء بدون خبرة؟", a: "نعم، مع متابعة المدرب." },
      { q: "كم كمية البروتين المطلوبة؟", a: "1.8 جرام لكل كجم من وزنك." },
    ],
  },
  {
    id: 3,
    slug: "general-fitness-12w",
    name: "اللياقة العامة",
    title: "اللياقة العامة — 12 أسبوع",
    subtitle: "برنامج تدريبي متوازن لتحسين الصحة واللياقة اليومية",
    goal: "fitness",
    duration: "12 أسبوع",
    durationWeeks: 12,
    level: "مبتدئ",
    difficulty: 2,
    sessionsPerWeek: 4,
    avgSessionMinutes: 40,
    homeFriendly: true,
    equipment: ["حصيرة", "دمبلز (اختياري)"],
    tags: ["لياقة", "صحة", "عامة"],
    price: { SAR: 249, original: 349, discountPercent: 29 },
    image: "/images/program-fitness.webp",
    hero: {
      image: "/images/program-fitness.webp",
      video: null,
    },
    badges: [
      { label: "12 أسبوع", type: "time" },
      { label: "4 جلسات/أسبوع", type: "sessions" },
      { label: "40 دقيقة", type: "time" },
      { label: "مبتدئ", type: "level" },
      { label: "منزلي", type: "home" },
    ],
    features: ["تمارين متنوعة", "تقوية القلب", "تحفيز مستمر"],
    overview: {
      about:
        "برنامج مثالي لتحسين اللياقة العامة، تقوية القلب، وزيادة النشاط اليومي بدون ضغط مفرط.",
      benefits: [
        "تحسين الصحة القلبية",
        "زيادة النشاط والطاقة",
        "تقليل التوتر",
        "تحسين المرونة",
      ],
      requirements: ["4 أيام أسبوعيًا", "اتباع الخطة", "الاهتمام بالتغذية"],
    },
    stats: {
      estCaloriesPerWeek: 1500,
      intensity: "متوسط",
    },
    weeks: [],
    nutrition: {
      macros: { calories: 2200, protein: 140, carbs: 250, fat: 60 },
      sampleMeals: [
        { meal: "فطور", items: ["بيض", "شوفان", "فواكه"] },
        { meal: "غداء", items: ["دجاج", "أرز بني", "سلطة"] },
        { meal: "سناك", items: ["زبادي", "تفاح"] },
        { meal: "عشاء", items: ["سمك", "بطاطا", "خضار"] },
      ],
      note: "التغذية متوازنة، لا حاجة لنظام صارم.",
    },
    trainers: [
      {
        id: "t3",
        name: "Coach Noura",
        avatar: "/images/CoachNoura.webp",
        rating: 4.6,
        certs: ["Fitness Coach", "Yoga"],
        bio: "متخصصة في اللياقة العامة والصحة النفسية.",
      },
    ],
    reviews: [
      {
        id: "r4",
        user: "Sara",
        rating: 4,
        text: "شعرت بتحسن كبير في طاقتي.",
        date: "2025-07-22",
      },
    ],
    faq: [
      { q: "هل يناسب كبار السن؟", a: "نعم، يمكن تعديل الشدة." },
      { q: "كم من الوقت أحتاج لرؤية النتائج؟", a: "من 4-6 أسابيع." },
    ],
  },
  {
    id: 4,
    slug: "personal-training-6m",
    name: "التدريب الشخصي",
    title: "التدريب الشخصي — 6 شهور",
    subtitle: "خطة مخصصة مع مدرب خاص وتغذية مصممة لك",
    goal: "personal",
    duration: "6 شهور",
    durationWeeks: 24,
    level: "جميع المستويات",
    difficulty: 5,
    sessionsPerWeek: 3,
    avgSessionMinutes: 60,
    homeFriendly: false,
    equipment: ["جيم", "مدرب"],
    tags: ["شخصي", "مخصص", "متابعات"],
    price: { SAR: 1499, original: 1999, discountPercent: 25 },
    image: "/images/program-personal.webp",
    hero: {
      image: "/images/program-personal.webp",
      video: null,
    },
    badges: [
      { label: "6 شهور", type: "time" },
      { label: "3 جلسات/أسبوع", type: "sessions" },
      { label: "60 دقيقة", type: "time" },
      { label: "مخصص", type: "personal" },
    ],
    features: ["مُدرب خاص", "خطة مخصصة", "دعم يومي"],
    overview: {
      about:
        "أفضل خيار للنتائج، مع مدرب خاص، خطة تدريب وتغذية مخصصة، ومتابعة يومية.",
      benefits: [
        "خطة تدريب مخصصة 100%",
        "تغذية مبنية على أهدافك",
        "دعم مباشر من المدرب",
        "تحديث أسبوعي للخطة",
      ],
      requirements: ["الالتزام", "الحضور المنتظم", "اتباع التغذية"],
    },
    stats: {
      estCaloriesPerWeek: 2000,
      intensity: "عالي",
    },
    weeks: [],
    nutrition: {
      macros: { calories: 2500, protein: 160, carbs: 280, fat: 70 },
      sampleMeals: [
        { meal: "فطور", items: ["بروتين", "شوفان", "فواكه"] },
        { meal: "غداء", items: ["دجاج", "أرز", "خضار"] },
        { meal: "سناك", items: ["زبادي", "مكسرات"] },
        { meal: "عشاء", items: ["لحم", "بطاطا", "سلطة"] },
      ],
      note: "تُخصص الخطة الغذائية حسب هدفك.",
    },
    trainers: [
      {
        id: "t4",
        name: "Coach Ali",
        avatar: "/images/CoachAli.webp",
        rating: 5.0,
        certs: ["Master Coach", "Nutritionist"],
        bio: "أفضل مدرب شخصي لدينا، مع 10 سنوات خبرة.",
      },
    ],
    reviews: [
      {
        id: "r5",
        user: "Mohammed",
        rating: 5,
        text: "غير حياتي، أنصح به بشدة.",
        date: "2025-07-25",
      },
    ],
    faq: [
      { q: "كيف يتم تحديد الخطة؟", a: "بعد تقييم أولي مع المدرب." },
      { q: "هل يمكنني تغيير المدرب؟", a: "نعم، في أي وقت." },
    ],
  },
  {
    id: 5,
    slug: "home-workouts-4w",
    name: "تمارين منزلية",
    title: "تمارين منزلية — 4 أسابيع",
    subtitle: "تمارين بدون أجهزة، مناسبة لكل المستويات",
    goal: "fitness",
    duration: "4 أسابيع",
    durationWeeks: 4,
    level: "مبتدئ",
    difficulty: 2,
    sessionsPerWeek: 5,
    avgSessionMinutes: 25,
    homeFriendly: true,
    equipment: ["حصيرة"],
    tags: ["منزلي", "بدون أجهزة", "مرن"],
    price: { SAR: 149, original: 199, discountPercent: 25 },
    image: "/images/program-home.webp",
    hero: {
      image: "/images/program-home.webp",
      video: null,
    },
    badges: [
      { label: "4 أسابيع", type: "time" },
      { label: "5 جلسات/أسبوع", type: "sessions" },
      { label: "25 دقيقة", type: "time" },
      { label: "مبتدئ", type: "level" },
      { label: "منزلي", type: "home" },
    ],
    features: ["بدون أجهزة", "مرونة في الوقت", "متابعات أسبوعية"],
    overview: {
      about:
        "تمارين منزلية بدون أجهزة، مناسبة لكل من يبحث عن مرونة في الوقت ولا يملك جهاز جيم.",
      benefits: [
        "لا حاجة لأجهزة",
        "مرونة في الوقت والموقع",
        "تحسين اللياقة العامة",
        "سهل المتابعة",
      ],
      requirements: ["مساحة صغيرة", "التزام 5 أيام", "اتباع التمارين"],
    },
    stats: {
      estCaloriesPerWeek: 1200,
      intensity: "منخفض إلى متوسط",
    },
    weeks: [],
    nutrition: {
      macros: { calories: 2000, protein: 130, carbs: 220, fat: 55 },
      sampleMeals: [
        { meal: "فطور", items: ["بيض", "شوفان", "فواكه"] },
        { meal: "غداء", items: ["دجاج", "أرز بني", "سلطة"] },
        { meal: "سناك", items: ["زبادي", "تفاح"] },
        { meal: "عشاء", items: ["سمك", "بطاطا", "خضار"] },
      ],
      note: "خطة غذائية بسيطة وسهلة الاتباع.",
    },
    trainers: [
      {
        id: "t5",
        name: "Coach Lina",
        avatar: "/images/CoachLina.webp",
        rating: 4.5,
        certs: ["Home Fitness", "CPT"],
        bio: "متخصصة في التمارين المنزلية.",
      },
    ],
    reviews: [
      {
        id: "r6",
        user: "Noor",
        rating: 4,
        text: "ممتاز للعمل من المنزل.",
        date: "2025-07-28",
      },
    ],
    faq: [
      { q: "هل يمكنني تأجيل يوم؟", a: "نعم، يمكن تعديل الجدول." },
      { q: "كم من الوقت أحتاج؟", a: "25 دقيقة يوميًا." },
    ],
  },
  {
    id: 6,
    slug: "transformation-12w",
    name: "برنامج التحول الشامل",
    title: "برنامج التحول الشامل — 12 أسبوع",
    subtitle: "تدريب + تغذية + دعم نفسي = تحول حقيقي",
    goal: "transformation",
    duration: "12 أسبوع",
    durationWeeks: 12,
    level: "متوسط",
    difficulty: 5,
    sessionsPerWeek: 6,
    avgSessionMinutes: 50,
    homeFriendly: false,
    equipment: ["جيم", "أوزان", "مدرب"],
    tags: ["تحول", "شامل", "نتائج"],
    price: { SAR: 899, original: 1199, discountPercent: 25 },
    image: "/images/program-transformation.webp",
    hero: {
      image: "/images/program-transformation.webp",
      video: null,
    },
    badges: [
      { label: "12 أسبوع", type: "time" },
      { label: "6 جلسات/أسبوع", type: "sessions" },
      { label: "50 دقيقة", type: "time" },
      { label: "متوسط", type: "level" },
      { label: "جيم", type: "gym" },
    ],
    features: ["تدريب + تغذية", "تغيير نمط الحياة", "نتائج مضمونة"],
    overview: {
      about:
        "برنامج شامل يجمع بين التدريب، التغذية، والدعم النفسي لتحقيق تحول جذري في 12 أسبوع.",
      benefits: [
        "نتائج مضمونة",
        "تغيير نمط الحياة",
        "دعم نفسي وتحفيزي",
        "متابعات يومية",
      ],
      requirements: ["التزام عالي", "حضور 6 أيام", "اتباع التغذية"],
    },
    stats: {
      estCaloriesPerWeek: 2200,
      intensity: "عالي",
    },
    weeks: [],
    nutrition: {
      macros: { calories: 2400, protein: 170, carbs: 260, fat: 65 },
      sampleMeals: [
        { meal: "فطور", items: ["بروتين", "شوفان", "فواكه"] },
        { meal: "غداء", items: ["دجاج", "أرز", "خضار"] },
        { meal: "سناك", items: ["زبادي", "مكسرات"] },
        { meal: "عشاء", items: ["لحم", "بطاطا", "سلطة"] },
      ],
      note: "تُخصص التغذية حسب التقدم.",
    },
    trainers: [
      {
        id: "t6",
        name: "Coach Eslam",
        avatar: "/images/CoachEslam.webp",
        rating: 4.8,
        certs: ["Transformation Coach", "Mindset"],
        bio: "متخصص في التحولات الشاملة.",
      },
    ],
    reviews: [
      {
        id: "r7",
        user: "Yasser",
        rating: 5,
        text: "أفضل برنامج جربته، غير حياتي.",
        date: "2025-07-30",
      },
    ],
    faq: [
      { q: "هل يناسب المبتدئين؟", a: "نعم، مع دعم إضافي." },
      { q: "ما هو معدل النجاح؟", a: "أكثر من 90% يحققون النتائج." },
    ],
  },
];

// دالة للحصول على البرنامج حسب الـ slug
export const getProgramBySlug = (slug) => {
  return programs.find((p) => p.slug === slug) || null;
};
